mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  # imu 
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:Imu 
    topic_from: /vectornav/imu
    topic_to: imu
  # magnetometer
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:MagneticField
    topic_from: /vectornav/magnetic_field
    topic_to: mag
  # GPS location
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:NavSatFix
    topic_from: /reach/rtk/fix
    topic_to: position
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: navcommand
    topic_to: /nav_command/command
  # mission topic for sending waypoints
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: set_scan_area
    topic_to: /nav_command/set_scan_area
  # mission topic for sending single waypoint
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: go_to_relative
    topic_to: /nav_command/go_to_relative
  # stop command to stop robot and clear current mission
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: stop
    topic_to: /navigation/stop
  # pause command to pause the robot or unpause the robot
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: pause
    topic_to: /navigation/pause
  # communicate current waypoint back to API
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:NavSatFix
    topic_from: /navigation/current_waypoint
    topic_to: current_waypoint
  # collision status
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /collision
    topic_to: collision
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64
    topic_from: /orientation
    topic_to: orientation
